### PR TITLE
added new button

### PR DESCRIPTION
**Pull request by Utkarsh750**
#What does this PR do?
 This PR added a new button on the project

fixes #21 
Screenshot (150)

### CODE REVIEW

**Comment by Utkarsh750** [comment]
hello sir, Could you please check my PR and merge it if I did right as it is my Career's first open-source contribution

**Comment by Utkarsh750** [comment]
please guide me

**Comment by parag477** [comment]
Nice work @Utkarsh750 Merging your PR

**Comment by Utkarsh750** [comment]
Thank you so much Sir, this simple step boost my confidence and help me to contribute more to in projects

**Comment by Utkarsh750** [comment]
Hello Sir ,
Hacktobetfest has just excluded your repository from the event why is that
happening

**Pull request merged**
